---
title: "Hw01_Gapminder"
author: "Matias"
date: '2018-09-16'
output: github_document
---

# Gapminder Exploration

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Load gapminder data

```{r}
require(gapminder)
```

## 2. How many rows and columns?

```{r}
nrow(gapminder)
ncol(gapminder)
```

## 3. There are 6 columns

```{r}
head(gapminder)
```

## 4. Lets explore GDP per capita

```{r}
mean(gapminder$gdpPercap)
median(gapminder$gdpPercap)
min(gapminder$gdpPercap)
max(gapminder$gdpPercap)
```

## 5. By loading the `tidyverse` package we can do more interesting analysis.

```{r}
library(tidyverse)
```

## 6. A comparison of lifeExp and gdpPercap by country, sorted by lifeExp first and then by gdpPercap.

```{r}
gapminder %>%
  select(lifeExp, gdpPercap, country) %>%
  arrange(lifeExp, gdpPercap)
```

## 7. A plot of lifeExp versus gdpPercap for all countries.

```{r}
ggplot(gapminder, aes(x = gdpPercap, y = lifeExp)) + geom_point()
plot <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp)) 
```

